## FIXME 配置security和配置git地址

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:hrt-eureka}:${EUREKA_PASSWORD:123456}@${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:9000}/eureka/

spring:
  application:
    name: config-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5673}
    username: ${RABBIT_MQ_USERNAME:rabbitmq}
    password: ${RABBIT_MQ_PASSWORD:123456}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HYUANT/hrt-microservice.git
          searchPaths: {application}

management:
  endpoints:
    web:
      exposure:
        include: '*'