## TODO 配置security

server:
  port: ${EUREKA_PORT:9000}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:hrt-eureka}:${EUREKA_PASSWORD:123456}@${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:9000}/eureka/

spring:
  application:
    name: eureka-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5673}
    username: ${RABBIT_MQ_USERNAME:rabbitmq}
    password: ${RABBIT_MQ_PASSWORD:123456}
  security:
    user:
      name: ${EUREKA_USERNAME:hrt-eureka}
      password: ${EUREKA_PASSWORD:123456}