version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: hrt-redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../data/redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: hrt-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672
      - 5673:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456

  mysql:
    image: mysql:5.7
    container_name: hrt-mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./init/sql:/docker-entrypoint-initdb.d
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456