server:
  port: 9017

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:hrt-eureka}:${EUREKA_PASSWORD:123456}@${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:9000}/eureka/

spring:
  application:
    name: turbine
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5673}
    username: ${RABBIT_MQ_USERNAME:rabbitmq}
    password: ${RABBIT_MQ_PASSWORD:123456}

turbine:
  stream:
    port: 9018

management:
  server:
    port: 9018
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: debug
  path: logs/
  file:
    max-size: 1GB